# **Introduction to NumPy and Matplotlib**
## **Modern Theory of Detection and Estimation** (Fall 2022)
### **Academic year 2022/2023**


------------------------------------------------------
The original version was prepared for *Master in Information Health Engineering* by:

*Harold Molina Bulla (h.molina@tsc.uc3m.es)*,
*Vanessa Gómez Verdejo (vanessa@tsc.uc3m.es)* and
*Pablo M. Olmos (olmos@tsc.uc3m.es)* 

------------------------------------------------------
  
    

# 1. What is NumPy?

[**Numerical Python**](http://www.numpy.org/) (usually known as NumPy) is the fundamental package for scientific computing with Python. It contains among other things:

- A powerful $N$-dimensional array object
- Sophisticated (broadcasting) functions 
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Let's load the library and start with some examples.

In [ ]:
import numpy as np  

# 2. Creating Arrays

NumPy is a Python library that lets you work with data vectors and matrices (we will call them NumPy arrays) and directly apply operations over these arrays without the need to operate element by element.

NumPy arrays can be defined directly using methods such as `.arange()`, `.ones()`, `.zeros()` or `.eye()`, as well as random number generators. Alternatively, you can easily generate them from python lists (or lists of lists) containing elements of a numerical type by using `np.array(my_list)`.

## 2.1 Designing 1-dimensional (1D) arrays (vectors)

 **Object:** `.array()`. This method returns an array or any (nested) sequence.


In [ ]:
v1=np.array([2,4,6]) #The default type is int32 or int64 since we did not use any decimal point
print("v1:", v1, "and its type is:", v1.dtype)

v2=np.array([2.0,4.0,6.0])
print("\nv2:", v2, "and its type is:", v2.dtype)

The array we just created is a **vector** or 1D array and it is characterized by a single dimension. 

(Please note the empty second entry when we call the method `.shape()`)

In [ ]:
print(v1.shape)

Let's transform `v1` into a 2-dimensional (2D) array (a matrix with a single column). How?

In [ ]:
v1 = np.reshape(v1,[v1.shape[0],1])
print('The shape of v1 is:', v1.shape)

We will see more in detail the object `.reshape()` later on, but if the curiosity gets the best of you, you can look at how this method works by yourself before ;)!

**Object:** `.arange()`. This method generates vectors of equally spaced numbers. We can specify start and stop positions as well as the step length (the steps don't need to be integers!). Let's see an example:

In [ ]:
print('A vector that goes from 2 to 8 in steps of 2: ', np.arange(2, 9, 1.5)) #start=2, stop=9 and step=1.5

**Object:** `.linspace()`. This method works exactly like its Matlab counterpart. We can specify start and stop positions as well as the number of samples to be generated. Please note, that in this case, the number of samples must be an integer.


In [ ]:
print('A vector of length 5 that spans from 0 to 1 in constant increments:', np.linspace(0, 1, 5)) #start=0, stop=0 and number of samples=5.

Plase notice the difference in the last number of the range for both methods. In `.arange()`, the last number is not included in the array, but in `.linspace()`, by default, the last namber is included.

**Object:** `.logspace()`. This method returns numbers spaced evenly on a log scale.

In [ ]:
v_log = np.logspace(0,10,10) # 10 elements equally spaced in the 10^0 (=1),10^10 range
print(v_log)

Try to guess, by yourself, how the rest of methods (such as, `.ones()`, `.eyes()` or .`zeros()`) work!

## 2.2 Designing arrays (matrices or tensors)

To correctly operate with NumPy arrays, we have to be aware of their dimensions. To understand this, let's start with a simple example:

 Are `array1` and `array2` equal?

In [ ]:
array1 = np.array([1,1,1])
print('Array1:\n', array1)

array2 = np.ones((1,3))
print('Array2:\n', array2)

Apparently, you would probably say that the only difference is the type of data of each array. But, let's check their shapes and dimensions.

In [ ]:
print('Shape of Array1 :',array1.shape)
print('Number of dimensions of Array1 :',array1.ndim)
print('Shape of Array2 :',array2.shape)
print('Number of dimensions of Array2 :',array2.ndim)

The only difference isn't the type of data, but also their dimensions! 

**Objects:** `.flatten()`, `.ravel()` and `.reshape()`. 

Effectively, `array1` is a 1D array, whereas `array2` is a 2D  array.  There are some methods that will let you modify the dimensions of an array. To convert a 2D into a 1D array, we have the methods `.flatten()`, `.ravel()` and `.reshape()`. Check the results of the following lines of code (you can use the help function to check the funcionalities of each method).

In [ ]:
x1 = np.arange(9).reshape((3, 3))
print('x1:\n', x1)
print('Its shape is: ', x1.shape)

In [ ]:
print('Use the method flatten:')
print('x1.flatten(): ', x1.flatten())
print('Its shape is: ', x1.flatten().shape)

In [ ]:
print('Use the method ravel:')
print('x1.ravel(): ', x1.ravel())
print('Its shape is:', x1.ravel().shape)

In [ ]:
print('Use the method reshape:')
print('x1.reshape(-1): ', x1.reshape(-1))
print('Its shape is: ', x1.reshape(-1).shape)

> Please note that here the method `.reshape()` is used to reorganize the matrix into a 1D array. A more common use of `.reshape()` is to simply redimension an array from shape `(i, j)` to shape `(t, r)` satisfying the condition that $i\times j = t\times r$. Let's see an example.


In [ ]:
print('Original x1:\n', x1)
x1 = np.arange(12).reshape((4, 3)) #In this example: i=4 and j=3
print('Its shape is: ', x1.shape)
print(" ")

print('\nx1.reshape((2,6)):\n', x1.reshape((2,6))) #t=2 and r=6
print('Now, its shape is: ', x1.reshape((2,6)).shape)

Apparently, `.flatten()`, `.ravel()` and `.reshape()` methods are similar. This is not true. 

`.flatten()` always returns a copy of the original vector, whereas `.ravel()` and `.reshape()` return a view of the original array whenever possible. That is, when using `.flatten()`, if you modify any value of this (flattened) array, it does not change the original array. Let's see this with an example.



In [ ]:
#ORIGINAL vector:
# Let's create an array
array1 = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the original array
print ("Original Array1: ") 
print(array1)


#RAVEL output:
print("\nOutput for RAVEL") 
array2 = array1.ravel()
# Ravel only passes a view of 
# original array to array 'b'
print('Array1 after .ravel()-> Array2 =', array2)
print('Let\'s change the first element of Array2 (Array2[0]=1000). Do Array1 and Array2 change?')
array2[0]=1000
print('Array2=', array2)
# Note here that value of original
# array 'a' at also a[0][0] becomes 1000
print('Array1 =\n', array1)
print('YES. They change!')

#FLATTEN output:
print("\nOutput for FLATTEN") 
array3 = array1.flatten()
  
# Flatten passes copy of
# original array to 'c'
print('Array1 after .flatten()-> Array3 =',array3)
print('Let\'s change the first element of Array3 (Array3[0]=5). Do Array1 and Array3 change?')
array3[0]=5
print('Array3=', array3)
# Note that by changing value of array3[0] there is no affect on value of original array1
print('Array1 =\n', array1)
print('Array3 has changed, but Array1 hasn\'t!')

**Object:** `.newaxis()`. Sometimes, we need to add a new dimension to an array, for example to turn a  1D array into a 2D column vector. For this purpose, we can use the method `.newaxis()`.

In [ ]:
# Let's start with a 1D array:
array1 = np.array([1,1,1])
print('1D array:\n',array1)
print('Its shape is: ', array1.shape)

# Let's turn it into a column vector (2D array with dimension 1x3):
array2 = array1[:,np.newaxis]
print('\n2D array:\n',array2)
print('Its shape is: ', array2.shape)

# Let's turn it into a row vector (2D array with dimension 3x1):
array3 = array1[np.newaxis,:]
print('\n2D array:\n',array3)
print('Its shape is: ', array3.shape)

**Object:** `.squeeze()`. Sometimes, we might also need to remove empty or unused dimensions. For this purpose, we cans use the method `.squeeze()`.

In [ ]:
print('- Original array:', array1, 'and its shape is:', array1.shape)
array1_1D = np.squeeze(array1)
print('1D array:',array1_1D, 'and its shape is:', array1_1D.shape)

print('\n- Original array:\n', array2, '\nand its shape is:', array2.shape)
array2_1D = np.squeeze(array2)
print('1D array:',array2_1D, 'and its shape is:', array2_1D.shape)

print('\n- Original array:', array3, 'and its shape is:', array3.shape)
array3_1D = np.squeeze(array3)
print('1D array:',array3_1D, 'and its shape is:', array3_1D.shape)


> Note that `array2` and `array3` have changed their dimensions!

There are other some interesting objects for this course!

**Object:** `.random.rand()`. It creates arrays where all elements are drawn from a **i.i.d uniform distribution**.

In [ ]:
m1=np.random.rand(15) #10 elements (one dimension)
print('m1:', m1)

M1=np.random.rand(3,5) #10 elements (two dimensions)
print('\nM1:', M1)

> The dimensions of `m1` and `M1` are different!

**Object:** `.random.normal()`. It creates arrays where all elements are drawn from a **normal (Gaussian) distribution**.

In [ ]:
mu = 0 #mean 
sigma = 0.01 #standard deviation
s = np.random.normal(mu, sigma, 10) #10 samples (or elements)
print('s:', s)

## 2.3 Indexing and slicing

Do you remember (from the first assigment lab) how to access to a specific position in a string? The idea is similar with arrays! 

(Note that the first element is indexed by 0).



In [ ]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])

In [ ]:
# Print the first element of F
# To fill in...


In [ ]:
# Print the last element of F
# To fill in..

### 2.3.1 Slicing

In NumPy, **slicing** means selecting and/or **accessing specific array rows and columns**.

Particular elements of NumPy arrays (both unidimensional and multidimensional) can be accessed using standard Python slicing. When working with multidimensional arrays, slicing can be carried out along several different dimensions at once. Let's see an example!



In [ ]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Try to guess the answer before executing the next lines of code!

In [ ]:
print(S[0:4])
print(S[:4])
print(S[6:])
print(S[:])
print(S[-2:])
print(S[:-3])

What happens when using matrices? Let's see an example.

In [ ]:
A = np.array([
[11,12,13,14,15],
[21,22,23,24,25],
[31,32,33,34,35],
[41,42,43,44,45],
[51,52,53,54,55]])
print("Matrix A:\n", A)

Try to guess the answer before executing the next lines of code!

In [ ]:
print(A[:3,2:])
print("")
print(A[3:,:])
print("")
print(A[:,4:])

**Object:** `.where(condition)`. 

We have seen how slicing allows us to index over the different dimensions of a given array. In the previous examples we learned how to select the rows and columns we're interested in, but how can we select only the elements of an array that meet a specific condition?

NumPy provides us with the method `.where(condition)`. A common way of using this method is by setting a condition involving an array. For example, the condition $x > 5$ will give us the indexes in which $x$ contains numbers higher than 5.

> **Exercise 1**: Let $\mathbf{x}$ be an array so that: $\mathbf{x} = [-3,-2,-1,0,1,2,3]$.

Now, create a new vector $\mathbf{y}$ with the elementos of $\mathbf{x}$, but replacing by $0$ each number whose absolute value is $2$ or less.

In [ ]:
# To fill in...

## 2.4 Concatenating arrays

**Objects:** `.hstack()` and `.vstack()`. Provided that the corresponding dimensions fit, horizontal and vertical stacking of matrices can be carried out by means of these two methods.

The method `np.vstack()` stacks arrays in sequence vertically (row wise).

The method `np.hstack()` stacks arrays in sequence horizontally (column wise).

> **Exercise**: Complete the following exercises to practice matrix concatenation. You can check your result by looking the solution in the next cell!

In [ ]:
import numpy as np
my_array = np.array([[1, -1, 3, 3],[2, 2, 4, 6]])
print('Array 1:')
print(my_array)
print(my_array.shape)

my_array2 = np.ones((2,3))
print('Array 2:')
print(my_array2)
print(my_array2.shape)


# Vertically stack matrix my_array with itself and call the resulting matrix 'ex1_res'
# To fill in...
print('Vertically stack:')
print(ex1_res)

# Horizontally stack matrix my_array and my_array2 and call the resulting matrix 'ex2_res'
# To fill in...
print('Horizontally stack:')
print(ex2_res)

The output should be:

```
Array 1:
[[ 1 -1  3  3]
 [ 2  2  4  6]]
(2, 4)
Array 2:
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
Vertically stack:
[[ 1 -1  3  3]
 [ 2  2  4  6]
 [ 1 -1  3  3]
 [ 2  2  4  6]]
Horizontally stack:
[[ 1. -1.  3.  3.  1.  1.  1.]
 [ 2.  2.  4.  6.  1.  1.  1.]]
 ```

## 2.5 Some operations with arrays

### 2.5.1 Element-wise operations

We can perform all the usual numerical and matrix operations with NumPy. In the case of matrix addition and subtraction, we can use the common "`+`" or "`-`" operators.

In [ ]:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3))
result = x1 + x2
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nAddition of x1 and x2 using the + operator:\n', result)

However, NumPy provides us with built-in functions (or methods) that guarantee that any errors and exceptions are handled properly.

In [ ]:
# We can add two matrices:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3))
result = np.add(x1, x2)
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nAddition of x1 and x2 using built-in functions:\n', result)

# Or compute the difference:
result = np.subtract(x1, x2)
print('\nSubtraction of x1 and x2 using built-in functions:\n', result)

We can also add or subtract column or row vectors from arrays. Again, both the basic operators and the built-in functions will perform the same operations. Unlike in Matlab, where this operation will raise an error, Python will automatically execute it row by row or column by column as appropriate.

In [ ]:
# We can add or subtract row and column vectors:
row_vect = np.ones((1, 3))
col_vect = 2*np.ones((3, 1))
result = np.add(x1, row_vect)
print('x1:\n', x1, '\n\nrow_vect:\n', row_vect, '\n\ncol_vect:\n', col_vect)
print('\nAddition of the row vector:\n', result)
result = np.add(x1, col_vect)
print('\nAddition of the column vector:\n', result)

Another key difference with Matlab is that the "`*`" operator won't give us matrix multiplication. It will instead compute an element-wise multiplication. Again, NumPy has a built-in function for this purpose that will guarantee propper handling of errors.

In [ ]:
# We can perform element-wise multiplication by using the * operator:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3)) * 2 # a 3x3 array with 2s in every element
result = x1 * x2
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nElement-wise multiplication of x1 and x2 using the * operator:\n', result)

# or by using the built-in numpy function:
result = np.multiply(x1, x2)
print('\nElement-wise multiplication of x1 and x2 using built-in functions:\n', result)


We can use the "`**`" operator or the method `.power()`
to raise elements from a matrix to a given power, or to raise elements of one matrix to positionally-corresponding powers in another matrix.




In [ ]:
  M = np.array([[1,2,3],[4,5,6]])
  print (M**2) #square each element of M

  print("\n", np.power(M,2))

Element-wise division between matrices is performed by using the ''`/`'' operator or the method `.divide()`.

In [ ]:
print(M/2)
M_div = np.divide(M,2)

print("\n",M_div)


Some other examples...

In [ ]:
print(np.log(M))
print(np.exp(M))

## 2.6 Matrix multiplication, inversion and pseudo-inverse

NumPy also gives us methods to perform matrix multiplications and dot products. The method `.dot()` is very powerful and can perform a number of different operations depending on the nature of the input arguments. For example, if we give it a pair of matrices of adequate dimensions, it will perform the same operation as `.matmul()`.

In [ ]:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3)) * 2 # a 3x3 array with 2s in every cell
result = np.matmul(x1, x2)
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nProduct of x1 and x2 using np.matmul():\n', result)

result = np.dot(x1, x2)
print('\nProduct of x1 and x2 using np.dot():\n', result, '\n')

In [ ]:
# Read the np.dot() documentation for more information:
help(np.dot)

Finally, we can transpose a matrix by using the method `.transpose()` or its abbreviated version `.T`. 

In [ ]:
# Three different ways of transposing a matrix:
x1 = np.arange(9).reshape((3, 3))
print('x1:\n', x1)
print('\nTranspose of x1 using the numpy function:\n', np.transpose(x1))
print('\nTranspose of x1 using the abbreviated form:\n', x1.T)
print('\nOddly enough, both methods produce the same result!')

## 2.7 Determinant and matrix inversion

Let it be `M2` as follows:

In [ ]:
M = np.random.randn(3,4)
M2=np.dot(M,M.transpose())

How to compute the determinant of a matrix `M2`?

In [ ]:
print('The determinant of M2 is:', (np.linalg.det(M2)))

And its inverse?

In [ ]:
M2I = np.linalg.inv(M2)
print('The inverse of M2 is:\n', M2I)

In [ ]:
#Let's check that the result is correct! (Note: In python 3.X, `np.dot` can  be replaced by `@`). Is the result equal to the identity matrix?
print(M2@M2I) 

### 2.7.1 Pseudoinverse

In mathematics, and in particular linear algebra, **a pseudoinverse** $A^+$ of a matrix $A$ is a generalization of the inverse matrix. The most widely known type of matrix pseudoinverse is the [Moore–Penrose inverse](http://mathworld.wolfram.com/Moore-PenroseMatrixInverse.html). 

When $A$ has linearly independent rows, i.e. $AA^*$ is invertible where $A^*$ is the Hermitian transpose, then the Pseudo-inverse $A^+$ can be computed as follows:

$$ A^+ = A^* (AA^*)^{-1} $$

and it verifies that $AA^+ =I$.


In [ ]:
M2PSI = np.linalg.pinv(M)

print(M@M2PSI)

print('\nSum of the diagonal elements:', round(np.trace(M @ M2PSI),1))
print('Sum of the out diagonal elements:',round(np.trace(M @ M2PSI)-np.sum(M @ M2PSI),1)) # Sum of out diagonal elements

# 3. Saving data with NumPy methods

The `.save()` method saves a NumPy array to a file, and the `.load()` method loads a NumPy array from a file. We need to specify the `.npy` extension for the files in both methods. 

The `.save()` method takes the name of the file and the array to save as input parameters and saves the array into the the specified file. The `.load()` method takes the filename as an input parameter and returns the array. Let's see an example.
 

In [ ]:
array = np.array([1, 3, 5, 7])

#Save the array in the file "test.npy"
np.save('test.npy', array)

#Load "test.npy" and return array2
array2 = np.load('test.npy')

#Are array and array2 the same?
print("Are the two arrays (array and array2) equal?:", np.array_equiv(array,array2))

# 4. Matplotlib

[Matplotlib](https://matplotlib.org/) is a Python 2D plotting library which produces figures in a variety of formats. Matplotlib can be used in Python scripts, the Python and IPython shells, the Jupyter notebook and web application servers.

Matplotlib tries to make easy things easy and hard things possible. You can generate plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc., with just a few lines of code. For example, see the sample plots and thumbnail gallery.

For simple plotting the `pyplot` module provides a MATLAB-like interface, particularly when combined with IPython. For the power user, you have full control of line styles, font properties, axes properties, etc., via an object oriented interface or via a set of functions familiar to MATLAB users.


In [ ]:
import matplotlib.pyplot as plt
#The following is required to print the plots inside the notebooks
%matplotlib inline 
%config InlineBackend.figure_format = 'retina' #High quality figures

## 4.1  Data generation

In Python, random samples can be easily generated with the `numpy.random` package. Inside it, we can find many usefull tools to sample from the most important probability distributions.

We have common number generator functions:
* `numpy.random.rand()`: It **uniformily** generates random samples.
* `numpy.random.randn()`: It returns samples from a **standard normal** distribution.

Or more specific ones:
* `numpy.random.exponential([scale, size])`: It draws samples from an exponential distribution with a given scale parameter.
* `numpy.random.normal([loc, scale, size])`:	It draws random samples from a normal (Gaussian) distribution with parameters: loc (mean) and scale (standard deviation).
* `numpy.random.uniform([low, high, size])`: It draws samples from a uniform distribution in the range low-high.

In the following examples we will look at different random generation methods and we will visualize the results. For the time being, you can ignore the visualization code. Later on we will learn how these visualization tools work.

In [ ]:
# Random samplig examples
n = 1000 # number of samples

# Sampling from a standard uniform distribution:
x_unif = np.random.rand(n)

fig1 = plt.figure()
plt.hist(x_unif, bins=100)
plt.title('Samples from a uniform distribution between 0 and 1')
plt.grid()
plt.show()

# Sampling from a normal distribution:
x_norm = np.random.randn(n)

fig2 = plt.figure()
plt.hist(x_norm, bins=100)
plt.title('Samples from a normal distribution with 0 mean and unity variance')
plt.grid()
plt.show()

# Adding Gaussian noise to a linear function:
n = 30
x = np.linspace(-5, 5, n)
noise = np.random.randn(n)
y = 3*x
y_noise = y + noise

fig3 = plt.figure()
plt.plot(x, y, color='black', linestyle='--', label='Clean signal')
plt.plot(x, y_noise, color='red', label='Noisy signal')
plt.legend(loc=4, fontsize='large')
plt.title('Visualization of a noisy data-set')
plt.grid()
plt.show()

#See https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html for more options!

More about plotting with `matplotlib`.

In [ ]:
t = np.arange(0.0, 1.0, 0.05) # Time vector, from 0s to 1s in steps of 0.05s.
a1 = np.sin(2*np.pi*t) # Samples of the first signal.
a2 = np.sin(4*np.pi*t) # Samples of the second signal.

# Visualization

# We can create a figure that will contain our plots.
plt.figure()
# We can plot the two signals in different subplots, as in Matlab.

# First signal
ax1 = plt.subplot(211)
ax1.plot(t,a1)
plt.title('First sinusoid.')
plt.xlabel('t (seconds)')
plt.ylabel('a_1(t)')

# Second signal
ax2 = plt.subplot(212)
ax2.plot(t,a2, 'r.')
plt.title('Second sinusoid.')
plt.xlabel('t (seconds)')
plt.ylabel('a_2(t)')


# We ensure the two plots won't overlap, and finally we show the results on the 
# screen.
plt.tight_layout()
plt.show()

Let's analyse how we have created the previous figures and in which things they differ:



*   A crucial aspect to consider is that **both curves represent a set of discrete samples** (the samples we've generated). While the second plot uses red dots to represent the data (specified through `'r.'`), the first one will draw the points using the standard blue line. As in Matlab, using lines to plot samples will interpolate them by default. If we don't want Matplotlib to do so, we can specify a different symbol, like dots, squares, etc.
*   We can label the axis and set titles, enhancing the way in which our data is presented. Moreover, we can improve the clarity of a figure by including or modyfing the line width, colours, symbols, legends, and a big etcetera. 

Look at the following figure and try to catch which argument and/or piece of code is related with each feature. It's intuitive! You can modify the parameters and see what's the new outcome. 


In [ ]:
t = np.arange(0.0, 3, 0.05)
a1 = np.sin(2*np.pi*t)+t 
a2 = np.ones(a1.shape)*t

plt.figure()
# We are going to plot two signals in the same figure. For each one we can
# specify colors, symbols, width, and the label to be displayed in a legend.
# Use the Matplotlib docs if you want to know all the things you can do. 
plt.plot(t,a1,'r--',LineWidth=2, label='Sinusoidal') 
plt.plot(t,a2, 'k:', label='Straight Line')


plt.title('Playing with different parameters')
plt.ylabel('Amplitude')
plt.xlabel('Time (seconds)')

# By default, axis limits will coincide with the highest/lowest values in our 
# vectors. However, we can specify ranges for x and y.
plt.xlim((-0.5, 3))
plt.ylim((-0.5, 4))

# When plotting more than one curve in a single figure, having a legend is a 
# good practice. You can ask Matplotlib to place it in the "best" position
# (trying not to overlap the lines), or you can specify positions like
# "upper left", "lower right"... check the docs!
plt.legend(loc='best')

# We can draw the origin lines, to separate the bidimensional space in four 
# quadrants.
plt.axhline(0,color='black')
plt.axvline(0, color='black')

# We can also set a grid with different styles... 
plt.grid(color='grey', linestyle='--', linewidth=0.8)

# And specify the "ticks", i.e., the values which are going to be specified in 
# the axis, where the grid method is placing lines. 
plt.xticks(np.arange(-0.5, 3, 0.5)) # In x, put a value each 0.5.
plt.yticks(np.arange(-0.5, 4, 1)) # In y, put a value each 1. 

# Finally, plot all the previous elements. 
plt.show()


In just a single example we have seen a lot of Matplotlib functionalities that can be easely tuned. You have all you need to draw decent figures. However, those of you who want to learn more about Matplotlib can take a look at [AnatomyOfMatplotlib](https://github.com/matplotlib/AnatomyOfMatplotlib), a collection of notebooks in which you will explore more in depth Matplotlib. 

Consider `x` a vector containing samples coming from a 1D random variable. A histogram is a figure in which we represent the observed frequencies of different ranges of the `x` domain. We can express them as relative frequencies (summing up to 1) or absolute frequencies (counting events). 

We can adapt the number and size of intervals (called bins) to directly affect the resolution of the plot. 

When we have a sufficiently high number of random samples coming from the same distribution, its histogram is expected to have a similar shape to the theoretical expression corresponding to the density of this distribution. 

In Matplotlib, we have already plotted histograms, with `plt.hist(samples,bins=)`.

Let's see some examples.

In [ ]:
# We take samples from a normalized gaussian distribution, and we change
# mean and variance with an operation.
sigma = 4
mn = 5
#x_gauss = mn + np.sqrt(sigma)*np.random.randn(5000)
x_gauss = np.random.normal(mn, sigma/2, 5000) #(easy way!!!)


# Let's obtain an histogram with high resultion, that is, a lot of bins.
fig1 = plt.figure()
plt.hist(x_gauss, bins=100,label='Samples')
plt.title('Histogram with 100 bins')

# With vertical lines, we plot the mean and the intervals obtain summing one 
# standard deviation to the mean. 
plt.axvline(x=np.mean(x_gauss),color='k',linestyle='--',label='Mean')
plt.axvline(x=np.mean(x_gauss)+np.std(x_gauss),color='grey',linestyle='--',label='Mean +/- std')
plt.axvline(x=np.mean(x_gauss)-np.std(x_gauss),color='grey',linestyle='--')


plt.legend(loc='best')
plt.show()

# We check that the mean and variance of the samples is aprox. the original one.
print('Sample mean = ', x_gauss.mean())
print('Sample variance = ', x_gauss.var())

# Now let's plot a low resolution histogram, with just a few bins.
fig2 = plt.figure()

# We can set weights in this way to obtain a normalized histogram, i.e.,
# expressing relative frequencies. 
w_n = np.zeros_like(x_gauss) + 1. / x_gauss.size

plt.hist(x_gauss, bins=10,label='Samples',weights=w_n)
plt.title('Histogram with 10 bins')
plt.axvline(x=np.mean(x_gauss),color='k',linestyle='--',label='Mean')
plt.axvline(x=np.mean(x_gauss)+np.std(x_gauss),color='grey',linestyle='--',label='Mean +/- std')
plt.axvline(x=np.mean(x_gauss)-np.std(x_gauss),color='grey',linestyle='--')
plt.legend(loc='best')
plt.show()

# A different resolution leads to different representations, but don't forget
# that we are plotting the same samples.

print('Sample mean = ', x_gauss.mean())
print('Sample variance = ', x_gauss.var())


## 4.2 More examples

### 4.2.1 Bar plot

The following code represents a bar plot with some predefined labels.


In [ ]:
labels = ['A','B','C','D','E','F','G']
values = np.array([1,2,5,8,5,1,0])

width = 0.35  # Bar width

x = np.arange(len(labels))

fig, ax = plt.subplots()
rect = ax.bar(x, values, width=width)
plt.grid(b=True, which='major', color='gray', alpha=0.6, linestyle='dotted', lw=1.5)
plt.xticks(x,labels)
plt.ylabel('Values')
plt.title('A bar plot')
plt.show()


### 4.2.2 Array of plots and text over figures

You can easily create arrays of plots to visualize them together. Here's an example. Also, we show how to include anotations in the figures.

In [ ]:
def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)

t1 = np.arange(0.0, 5.0, 0.1)
t2 = np.arange(0.0, 5.0, 0.02)

plt.figure()
plt.subplot(211)
plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')
num_figure = 1
plt.annotate('local max', xy=(1, f(1)), xytext=(1.25, 0.85),
             arrowprops=dict(facecolor='red', width = 1))
plt.text(4, 0.75, "Figura {0:d}".format(num_figure))
plt.grid()

plt.subplot(212)
plt.plot(t2, np.cos(2*np.pi*t2), 'r--')

plt.text(6, 0, "Figure {0:d}".format(num_figure+1), style='italic',
        bbox={'facecolor': 'blue', 'alpha': 0.1, 'pad': 10})
plt.grid()
plt.show()

### 4.2.3 Contour and surface plots

These plots are handy to represent functions over 2D spaces. 


In [ ]:
# We consider the following function with 2D inputs

def f(x,y):
    return np.exp((+x**2-y**2+x*y+x-y)/20)

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

# Lets start with a contour plot

grid_points = 100
lims = 4
# Grid of grid_points**2 points in the [-2,2] square
x,y = np.mgrid[-lims:lims:2*lims/grid_points, -lims:lims:2*lims/grid_points]
grid = np.transpose(np.row_stack([x.ravel(), y.ravel()]))

# Lets evaluate the function over the grid

f_grid = f(grid[:,0],grid[:,1]).reshape([grid_points,grid_points])

fig = plt.figure(figsize=(6, 18))

# Contour lines
plt.subplot(311)
plt.contour(x,y,f_grid,np.arange(0,1,0.05),cmap='coolwarm') # We plot the 0, 0.1, 0.2, ..., 1.0 contour lines
plt.colorbar()
plt.grid()
plt.title("Contour lines")

# Contour plot
plt.subplot(312)
plt.contourf(x,y,f_grid,cmap='coolwarm') 
plt.colorbar()
plt.grid()
plt.title("Contour plot")

# Surface plot
ax = fig.add_subplot(3, 1, 3, projection='3d')
ax.plot_surface(x,y,f_grid,cmap='coolwarm') 
plt.colorbar()
plt.grid()
plt.title("Surface plot")

plt.show()

